spring:
  data:
    mongodb:
      host: 192.168.1.206
      port: 27017
      database: cms
ibabygroup:
  rest:
    token: XRbghp7zHw8Yx6gX
    count: http://192.168.1.203:8080/REST/pulpitservice/userList
    detail: http://192.168.1.203:8080/pulpitServer/pulpitMember/searchTodayAllPulpitBg
    isOpen: true
  imService:
    host: http://192.168.1.203:9696